### ISSUE TITLE
안녕하세요. 해당 오픈소스가 혹시 tizen native headed 5.5 혹은 6.0에서 개발이 가능한가요?

### ISSUE THREAD

**Issue by ingbeeedd** [melchi45/mosquitto-tizen#1]
안녕하세요. 타이젠 초보 개발자라는 점 먼저 말씀드립니다
타이젠 스튜디오에서 타겟은 라즈베리파이 + headed 5.5 혹은 6.0입니다
라즈베리파이에서 mqtt 서버와 subscriber를 동시에 실행시키고 싶은데, 해당 API 소스로 가능한가요?

**Comment by melchi45** [comment]
예. 단순 브로커로  mqtt 수발신 테스트만 했습니다.

2020년 8월 17일 (월) 오후 10:37, ingbeeedd <notifications@github.com>님이 작성:

**Comment by melchi45** [comment]
라즈베리에 굳이 타이젠을 쓰시는 건가요?

2020년 8월 20일 (목) 오전 10:34, 김영호 <melchi45@gmail.com>님이 작성:

**Comment by ingbeeedd** [comment]
네 타이젠을 사용해야 하는 대회라서요..

**Comment by ingbeeedd** [comment]
데이터 전송을 단순하게 웹서버로 할까 생각합니다. mqtt 사용이 어렵나요?

**Comment by melchi45** [comment]
mqtt 자체는 어렵지 않지만, iot를 할거라면 ocf표준을 구현해야해서 해야할게 많습니다.

Good luck to you.

2020년 8월 20일 (목) 오전 10:45, ingbeeedd <notifications@github.com>님이 작성:
